name: DouglasvilleAttorney
favicon: null
layout_spectrum: 0.3776131810154766
typography_spectrum: 0.31566244130954146
title: Douglasville Attorney Ed Napier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0033a9'
    - '#4d70c4'
    - '#a8a9ad'
    - '#bfcdea'
  brandStrength: 0.5
  lightness: 0.5743879340589046
  saturation: 0.8037307066842914
  rhythmicContrast: 0.6489385487511754
purpose: []
