name: DouglasvilleAttorney
favicon: null
layout_spectrum: 1
typography_spectrum: 0.99119
title: Douglasville Criminal Defense Attorney
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0033a9'
    - '#4d70c4'
    - '#a8a9ad'
    - '#bfcdea'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
